/**
 * DENVER DEMONSTRATION DATASET — SIMULATED DATA.
 *
 * Real places, approximate locations, and representative (not live) hours.
 * Hours are marked "verified" so the demo exercises the same hard gate the
 * live engine uses; the UI labels everything from this file as DEMO DATA.
 */
import type { Place, PlaceAttributes, ParkingInfo, Interest, WeeklyHours, ActivityWindow, HoursData } from '@/core/types';
import { H } from '@/core/hours';

export const DENVER_TZ = 'America/Denver';
export const DENVER_CENTER = { lat: 39.7392, lng: -104.9903 };
export const DEMO_DATASET_LABEL = 'Denver demo dataset · simulated hours, weather, traffic and parking';

const HOLIDAYS_CLOSED: Record<string, 'closed'> = { '2026-11-26': 'closed', '2026-12-25': 'closed', '2027-01-01': 'closed' };

const t = H.t;

interface Spec {
  id: string;
  name: string;
  summary: string;
  pitch: string;
  cats: Interest[];
  tags?: string[];
  lat: number;
  lng: number;
  hood: string;
  setting: Place['setting'];
  price: Place['priceLevel'];
  cost?: string;
  dur: [number, number];
  weekly: WeeklyHours;
  overrides?: HoursData['overrides'];
  season?: HoursData['season'];
  temporarilyClosed?: boolean;
  unknownHours?: boolean;
  activities?: ActivityWindow[];
  attrs?: Partial<PlaceAttributes>;
  exposure: PlaceAttributes['exposure'];
  parking: ParkingInfo | null;
  rating?: number;
  url?: string;
}

function make(s: Spec): Place {
  return {
    id: `dnv-${s.id}`,
    name: s.name,
    summary: s.summary,
    pitch: s.pitch,
    categories: s.cats,
    tags: s.tags ?? [],
    location: { lat: s.lat, lng: s.lng },
    neighborhood: s.hood,
    timezone: DENVER_TZ,
    setting: s.setting,
    priceLevel: s.price,
    costNote: s.cost,
    duration: { min: s.dur[0], typical: s.dur[1] },
    hours: {
      confidence: s.unknownHours ? 'unknown' : 'verified',
      verifiedThrough: s.unknownHours ? undefined : '2030-12-31',
      weekly: s.weekly,
      overrides: s.overrides ?? HOLIDAYS_CLOSED,
      season: s.season,
      temporarilyClosed: s.temporarilyClosed,
    },
    activities: s.activities,
    attributes: { exposure: s.exposure, ...s.attrs },
    parking: s.parking,
    rating: s.rating,
    url: s.url,
    source: 'demo',
  };
}

const EASY_FREE: ParkingInfo = { difficulty: 'easy', cost: 'Free lot', type: 'lot', walkMin: 3 };
const EASY_LOT: ParkingInfo = { difficulty: 'easy', cost: 'Free lot', type: 'lot', walkMin: 2 };
const STREET_MOD: ParkingInfo = { difficulty: 'moderate', cost: 'Metered street, ~$2/hr', type: 'street', walkMin: 5 };
const GARAGE_HARD: ParkingInfo = { difficulty: 'hard', cost: '$15–25 garage', type: 'garage', walkMin: 7 };
const GARAGE_MOD: ParkingInfo = { difficulty: 'moderate', cost: '$8–15 garage', type: 'garage', walkMin: 4 };
const NONE_HARD: ParkingInfo = { difficulty: 'hard', cost: 'Street only, scarce', type: 'street', walkMin: 8 };

const museumLastEntry = (closeMin: number, before = 30): ActivityWindow => ({
  label: 'Last entry',
  kind: 'lastEntry',
  weekly: H.daily(0, closeMin - before),
  mustCover: 'arrival',
});

export const DENVER_PLACES: Place[] = [
  make({
    id: 'red-rocks', name: 'Red Rocks Park & Amphitheatre',
    summary: 'Sandstone monoliths, trails and the famous amphitheatre, 15 miles west of town.',
    pitch: 'Walk the amphitheatre steps, hike Trading Post Trail, and get the big-sky view everyone talks about.',
    cats: ['outdoors', 'scenic', 'active', 'tourist'], tags: ['park', 'hike', 'views'],
    lat: 39.6654, lng: -105.2057, hood: 'Morrison', setting: 'outdoor', price: 0, cost: 'Free (non-event days)',
    dur: [60, 120], weekly: H.daily(t(5), t(23)), overrides: {}, exposure: 'full',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: true, walkable: false, transitFriendly: false },
    parking: EASY_FREE, rating: 4.9, url: 'https://www.redrocksonline.com',
  }),
  make({
    id: 'dam', name: 'Denver Art Museum',
    summary: 'Two striking buildings of Indigenous, Western and contemporary art in the Golden Triangle.',
    pitch: 'The Martin Building atrium alone is worth it. Free for kids under 18.',
    cats: ['arts', 'tourist', 'relaxed'], tags: ['museum'],
    lat: 39.7372, lng: -104.9894, hood: 'Golden Triangle', setting: 'indoor', price: 2, cost: '$22 adults · kids free',
    dur: [90, 150], weekly: H.days({ 2: [{ open: t(10), close: t(17) }], 3: [{ open: t(10), close: t(17) }], 4: [{ open: t(10), close: t(17) }], 5: [{ open: t(10), close: t(17) }], 6: [{ open: t(10), close: t(17) }], 0: [{ open: t(10), close: t(17) }] }),
    activities: [museumLastEntry(t(17), 30)], exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, transitFriendly: true, walkable: true },
    parking: GARAGE_MOD, rating: 4.7, url: 'https://www.denverartmuseum.org',
  }),
  make({
    id: 'botanic', name: 'Denver Botanic Gardens',
    summary: '24 acres of themed gardens plus a tropical conservatory on York Street.',
    pitch: 'The Japanese garden at golden hour is the move. Conservatory keeps it going in bad weather.',
    cats: ['outdoors', 'scenic', 'relaxed', 'romantic'], tags: ['garden'],
    lat: 39.7321, lng: -104.9602, hood: 'Cheesman Park', setting: 'mixed', price: 2, cost: '$15.75 adults',
    dur: [75, 120], weekly: H.daily(t(9), t(17)), activities: [museumLastEntry(t(17), 60)], exposure: 'partial',
    attrs: { kidFriendly: true, accessible: true, transitFriendly: true, walkable: true },
    parking: { difficulty: 'moderate', cost: 'Free garage, fills by noon', type: 'garage', walkMin: 3 }, rating: 4.8,
  }),
  make({
    id: 'union-station', name: 'Union Station',
    summary: 'Restored 1914 rail hall with bars, restaurants and the Terminal Bar in the Great Hall.',
    pitch: 'Grab a drink in the Great Hall, people-watch, then walk to anything in LoDo.',
    cats: ['history', 'food', 'tourist', 'local', 'nightlife'], tags: ['landmark'],
    lat: 39.753, lng: -104.9999, hood: 'LoDo', setting: 'indoor', price: 2, cost: 'Free to visit',
    dur: [45, 90], weekly: H.daily(t(5), t(25)), overrides: {}, exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, transitFriendly: true, walkable: true, dogFriendly: false },
    parking: GARAGE_HARD, rating: 4.7,
  }),
  make({
    id: 'rino-murals', name: 'RiNo mural walk',
    summary: 'Self-guided walk through the densest stretch of street art in the city.',
    pitch: 'Start at Larimer & 27th, zigzag the alleys, end at a brewery. Free and always changing.',
    cats: ['arts', 'local', 'weird', 'scenic', 'active'], tags: ['walk', 'street art'],
    lat: 39.762, lng: -104.98, hood: 'RiNo', setting: 'outdoor', price: 0,
    dur: [45, 90], weekly: H.daily(t(7), t(19)), overrides: {}, exposure: 'full',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: STREET_MOD, rating: 4.6,
  }),
  make({
    id: 'central-market', name: 'Denver Central Market',
    summary: 'Food hall in a 1920s warehouse: oysters, pizza, tacos, ice cream, coffee.',
    pitch: 'Everyone gets what they want, nobody waits for a table.',
    cats: ['food', 'coffee', 'local', 'family'], tags: ['food hall'],
    lat: 39.7606, lng: -104.981, hood: 'RiNo', setting: 'indoor', price: 2, cost: '$12–25 per person',
    dur: [45, 75], weekly: H.daily(t(8), t(21)), exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true, dogFriendly: false },
    parking: STREET_MOD, rating: 4.6,
  }),
  make({
    id: 'dmns', name: 'Denver Museum of Nature & Science',
    summary: 'Dinosaurs, space, a planetarium and an IMAX, on the east edge of City Park.',
    pitch: 'The best rainy-day move with kids in Denver. Space Odyssey wing is a crowd-pleaser.',
    cats: ['family', 'history', 'tourist', 'relaxed'], tags: ['museum', 'science'],
    lat: 39.7475, lng: -104.9428, hood: 'City Park', setting: 'indoor', price: 2, cost: '$25.95 adults · $19.95 kids',
    dur: [120, 180], weekly: H.daily(t(9), t(17)), activities: [museumLastEntry(t(17), 60)], exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, transitFriendly: true },
    parking: EASY_LOT, rating: 4.8,
  }),
  make({
    id: 'city-park', name: 'City Park',
    summary: "Denver's biggest park: two lakes, a boathouse, skyline-and-mountains views.",
    pitch: 'Loop the lake, rent a pedal boat in summer, catch the skyline from the east side.',
    cats: ['outdoors', 'family', 'relaxed', 'active', 'scenic'], tags: ['park'],
    lat: 39.7472, lng: -104.95, hood: 'City Park', setting: 'outdoor', price: 0,
    dur: [45, 90], weekly: H.daily(t(5), t(23)), overrides: {}, exposure: 'full',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: EASY_FREE, rating: 4.7,
  }),
  make({
    id: 'wash-park', name: 'Washington Park',
    summary: 'The classic Denver park: 2.6-mile loop, flower gardens, two lakes.',
    pitch: 'Walk or run the loop, then hit Old South Gaylord for coffee.',
    cats: ['outdoors', 'active', 'relaxed', 'local'], tags: ['park', 'run'],
    lat: 39.7, lng: -104.9705, hood: 'Wash Park', setting: 'outdoor', price: 0,
    dur: [45, 90], weekly: H.daily(t(5), t(23)), overrides: {}, exposure: 'full',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: true, walkable: true, transitFriendly: false },
    parking: STREET_MOD, rating: 4.8,
  }),
  make({
    id: 'meow-wolf', name: 'Meow Wolf Convergence Station',
    summary: 'Four floors of immersive, walk-through art installations under the highway overpass.',
    pitch: 'Genuinely unlike anything else. Give it two hours and get lost on purpose.',
    cats: ['weird', 'arts', 'family', 'tourist'], tags: ['immersive'],
    lat: 39.7406, lng: -105.0118, hood: 'Sun Valley', setting: 'indoor', price: 3, cost: '$45–55 adults',
    dur: [120, 180],
    weekly: H.days({ 0: [{ open: t(10), close: t(22) }], 1: [{ open: t(10), close: t(22) }], 2: [{ open: t(10), close: t(22) }], 3: [{ open: t(10), close: t(22) }], 4: [{ open: t(10), close: t(22) }], 5: [{ open: t(10), close: t(24) }], 6: [{ open: t(10), close: t(24) }] }),
    activities: [{ label: 'Last entry', kind: 'lastEntry', mustCover: 'arrival', weekly: H.days({ 0: [{ open: t(10), close: t(20) }], 1: [{ open: t(10), close: t(20) }], 2: [{ open: t(10), close: t(20) }], 3: [{ open: t(10), close: t(20) }], 4: [{ open: t(10), close: t(20) }], 5: [{ open: t(10), close: t(22) }], 6: [{ open: t(10), close: t(22) }] }) }],
    exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, reservationRecommended: true, transitFriendly: true },
    parking: { difficulty: 'moderate', cost: '$10 lot', type: 'lot', walkMin: 3 }, rating: 4.7,
  }),
  make({
    id: 'larimer-square', name: 'Larimer Square',
    summary: "Denver's oldest block: string lights, boutiques, and a dense run of restaurants.",
    pitch: 'Best at dusk when the lights come on. Great for a wander before dinner.',
    cats: ['shopping', 'food', 'nightlife', 'tourist', 'romantic'], tags: ['district'],
    lat: 39.7478, lng: -104.9988, hood: 'LoDo', setting: 'mixed', price: 2,
    dur: [45, 90], weekly: H.daily(t(10), t(22)), exposure: 'partial',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true, dogFriendly: true },
    parking: GARAGE_HARD, rating: 4.5,
  }),
  make({
    id: 'tattered-cover', name: 'Tattered Cover Book Store',
    summary: 'The beloved independent bookstore, Colfax location, with deep couches and a café.',
    pitch: 'The kind of place you go in for one book and leave two hours later.',
    cats: ['shopping', 'relaxed', 'local', 'coffee'], tags: ['bookstore'],
    lat: 39.7402, lng: -104.956, hood: 'Colfax', setting: 'indoor', price: 1,
    dur: [30, 75], weekly: H.daily(t(9), t(20)), exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, transitFriendly: true, walkable: true },
    parking: EASY_LOT, rating: 4.7,
  }),
  make({
    id: 'little-man', name: 'Little Man Ice Cream',
    summary: 'Ice cream scooped out of a 28-foot milk can in LoHi. A line is part of the deal.',
    pitch: 'Salted Oreo. Then walk the Highland Bridge for the skyline.',
    cats: ['food', 'family', 'weird', 'local'], tags: ['dessert'],
    lat: 39.7572, lng: -105.0105, hood: 'LoHi', setting: 'outdoor', price: 1, cost: '$6–9',
    dur: [20, 40], weekly: H.daily(t(11), t(23)), exposure: 'partial',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: NONE_HARD, rating: 4.8,
  }),
  make({
    id: 'corvus', name: 'Corvus Coffee Roasters',
    summary: 'Serious single-origin roaster on South Broadway with a calm, sunny room.',
    pitch: 'Pour-over worth the wait. Pairs with a South Broadway shop crawl.',
    cats: ['coffee', 'local', 'relaxed'], tags: ['cafe'],
    lat: 39.7001, lng: -104.9874, hood: 'Platt Park', setting: 'indoor', price: 1, cost: '$5–8',
    dur: [25, 45], weekly: H.daily(t(7), t(18)), exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true, dogFriendly: true },
    parking: STREET_MOD, rating: 4.7,
  }),
  make({
    id: 'huckleberry', name: 'Huckleberry Roasters — Dairy Block',
    summary: 'Bright local roaster inside the Dairy Block alley, steps from Coors Field.',
    pitch: 'Quick, good, central. The right first stop before a LoDo walk.',
    cats: ['coffee', 'local'], tags: ['cafe'],
    lat: 39.7538, lng: -104.9965, hood: 'LoDo', setting: 'indoor', price: 1, cost: '$5–7',
    dur: [20, 40], weekly: H.daily(t(7), t(17)), exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true, dogFriendly: true },
    parking: GARAGE_HARD, rating: 4.6,
  }),
  make({
    id: 'zoo', name: 'Denver Zoo',
    summary: '80 acres in City Park with elephants, big cats and a very good penguin exhibit.',
    pitch: 'Go early, loop clockwise, and you beat both the crowds and the heat.',
    cats: ['family', 'outdoors', 'tourist', 'active'], tags: ['zoo'],
    lat: 39.7503, lng: -104.95, hood: 'City Park', setting: 'mixed', price: 3, cost: '$25–30 adults',
    dur: [120, 180], weekly: H.daily(t(10), t(17)), activities: [museumLastEntry(t(17), 60)], exposure: 'partial',
    attrs: { kidFriendly: true, accessible: true, transitFriendly: true, dogFriendly: false },
    parking: EASY_FREE, rating: 4.6,
  }),
  make({
    id: 'mount-falcon', name: 'Mount Falcon Park (east trailhead)',
    summary: 'Foothills hiking with castle ruins and wide views, 20 miles southwest.',
    pitch: 'Castle Trail to the Walker Home ruins is 7 miles round trip; Turkey Trot loop is the short version.',
    cats: ['outdoors', 'active', 'scenic'], tags: ['hike'],
    lat: 39.642, lng: -105.225, hood: 'Morrison', setting: 'outdoor', price: 0,
    dur: [90, 180], weekly: H.daily(t(6), t(19)), overrides: {}, exposure: 'full',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: false, transitFriendly: false },
    parking: { difficulty: 'moderate', cost: 'Free lot, fills on weekends', type: 'lot', walkMin: 2 }, rating: 4.8,
  }),
  make({
    id: 'clear-creek', name: 'Clear Creek Trail — downtown Golden',
    summary: 'Flat creekside path through Golden, with tubing in summer and cafés on Washington Ave.',
    pitch: 'Easy stroll, mountain backdrop, and ice cream afterward. Works for every age and the dog.',
    cats: ['outdoors', 'scenic', 'local', 'relaxed', 'family'], tags: ['walk', 'creek'],
    lat: 39.7555, lng: -105.2211, hood: 'Golden', setting: 'outdoor', price: 0,
    dur: [45, 90], weekly: H.daily(t(5), t(23)), overrides: {}, exposure: 'full',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: true, walkable: true },
    parking: EASY_FREE, rating: 4.8,
  }),
  make({
    id: 'linger', name: 'Linger',
    summary: 'Globally inspired small plates in a former mortuary, with a rooftop that faces downtown.',
    pitch: 'Book the rooftop for sunset. The building really was a mortuary.',
    cats: ['food', 'romantic', 'scenic', 'nightlife'], tags: ['restaurant', 'rooftop'],
    lat: 39.7577, lng: -105.009, hood: 'LoHi', setting: 'mixed', price: 3, cost: '$40–60 per person',
    dur: [75, 120],
    weekly: H.days({ 1: [{ open: t(16), close: t(22) }], 2: [{ open: t(11, 30), close: t(22) }], 3: [{ open: t(11, 30), close: t(22) }], 4: [{ open: t(11, 30), close: t(22) }], 5: [{ open: t(11, 30), close: t(23) }], 6: [{ open: t(10), close: t(23) }], 0: [{ open: t(10), close: t(21) }] }),
    activities: [{ label: 'Kitchen', kind: 'kitchen', mustCover: 'visit', weekly: H.days({ 1: [{ open: t(16), close: t(21, 30) }], 2: [{ open: t(11, 30), close: t(21, 30) }], 3: [{ open: t(11, 30), close: t(21, 30) }], 4: [{ open: t(11, 30), close: t(21, 30) }], 5: [{ open: t(11, 30), close: t(22, 30) }], 6: [{ open: t(10), close: t(22, 30) }], 0: [{ open: t(10), close: t(20, 30) }] }) }],
    exposure: 'partial',
    attrs: { reservationRecommended: true, accessible: true, walkable: true, transitFriendly: true, kidFriendly: true },
    parking: NONE_HARD, rating: 4.6,
  }),
  make({
    id: 'snooze', name: 'Snooze, an A.M. Eatery — Union Station',
    summary: 'Pancake flights and a very cheerful line. Breakfast and lunch only.',
    pitch: 'Pineapple upside-down pancakes. Go before 9 or after 1 to skip the wait.',
    cats: ['food', 'family', 'local'], tags: ['breakfast'],
    lat: 39.7538, lng: -104.9992, hood: 'LoDo', setting: 'indoor', price: 2, cost: '$15–22 per person',
    dur: [45, 75], weekly: H.daily(t(6, 30), t(14, 30)), exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: GARAGE_HARD, rating: 4.5,
  }),
  make({
    id: 'casa-bonita', name: 'Casa Bonita',
    summary: 'The pink palace in Lakewood: cliff divers, Black Bart\'s cave, sopapillas, 52,000 square feet of it.',
    pitch: 'Reservations only, and worth planning around. Kids lose their minds.',
    cats: ['weird', 'family', 'food', 'tourist'], tags: ['restaurant', 'attraction'],
    lat: 39.7408, lng: -105.0806, hood: 'Lakewood', setting: 'indoor', price: 3, cost: '$40 adults · $25 kids',
    dur: [120, 180],
    weekly: H.days({ 3: [{ open: t(11), close: t(21) }], 4: [{ open: t(11), close: t(21) }], 5: [{ open: t(11), close: t(22) }], 6: [{ open: t(11), close: t(22) }], 0: [{ open: t(11), close: t(21) }] }),
    exposure: 'none',
    attrs: { reservationRequired: true, kidFriendly: true, accessible: true, transitFriendly: false },
    parking: EASY_FREE, rating: 4.4,
  }),
  make({
    id: 'sushi-den', name: 'Sushi Den',
    summary: 'Fish flown in daily from Japan to Old South Pearl. Dinner only.',
    pitch: 'The best sushi between the coasts. Sit at the bar if you can.',
    cats: ['food', 'romantic', 'local'], tags: ['restaurant', 'sushi'],
    lat: 39.7097, lng: -104.9803, hood: 'Platt Park', setting: 'indoor', price: 3, cost: '$50–80 per person',
    dur: [75, 120],
    weekly: H.days({ 1: [{ open: t(16, 45), close: t(22)}], 2: [{ open: t(16, 45), close: t(22) }], 3: [{ open: t(16, 45), close: t(22) }], 4: [{ open: t(16, 45), close: t(22) }], 5: [{ open: t(16, 45), close: t(22, 30) }], 6: [{ open: t(16, 45), close: t(22, 30) }], 0: [{ open: t(16, 45), close: t(21, 30) }] }),
    exposure: 'none',
    attrs: { reservationRecommended: true, accessible: true, walkable: true, kidFriendly: true },
    parking: STREET_MOD, rating: 4.7,
  }),
  make({
    id: 'petes-kitchen', name: "Pete's Kitchen",
    summary: 'Colfax diner institution. Breakfast burritos smothered in green chile until the small hours.',
    pitch: 'The late-night answer. Cash is faster.',
    cats: ['food', 'local', 'weird', 'nightlife'], tags: ['diner', 'late night'],
    lat: 39.7402, lng: -104.9655, hood: 'Colfax', setting: 'indoor', price: 1, cost: '$10–16',
    dur: [30, 60], weekly: H.daily(t(6), t(26)), overrides: {}, exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: EASY_LOT, rating: 4.4,
  }),
  make({
    id: 'biker-jims', name: "Biker Jim's Gourmet Dogs",
    summary: 'Reindeer, elk and wild boar dogs with cream cheese squirted from a caulk gun.',
    pitch: 'Weird, fast, and legitimately good. Ten minutes from anything downtown.',
    cats: ['food', 'weird', 'local'], tags: ['hot dogs', 'quick'],
    lat: 39.7498, lng: -104.9939, hood: 'Downtown', setting: 'indoor', price: 1, cost: '$9–14',
    dur: [20, 40], weekly: H.daily(t(11), t(21)), exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: NONE_HARD, rating: 4.5,
  }),
  make({
    id: 'avanti', name: 'Avanti Food & Beverage',
    summary: 'Shipping-container food hall in LoHi with two rooftop decks facing the skyline.',
    pitch: 'Seven kitchens, one view. Sunset on the upper deck is the whole point.',
    cats: ['food', 'local', 'scenic', 'nightlife'],
    tags: ['food hall', 'rooftop'],
    lat: 39.7579, lng: -105.0081, hood: 'LoHi', setting: 'mixed', price: 2, cost: '$14–24 per person',
    dur: [60, 90], weekly: H.daily(t(11), t(22)),
    activities: [{ label: 'Kitchens', kind: 'kitchen', mustCover: 'visit', weekly: H.daily(t(11), t(21)) }],
    exposure: 'partial',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true, dogFriendly: true },
    parking: NONE_HARD, rating: 4.5,
  }),
  make({
    id: 'denver-beer-co', name: 'Denver Beer Co — Platte Street',
    summary: 'Garage-door taproom with a big dog-friendly patio and rotating food trucks.',
    pitch: 'The patio with the dog, a Graham Cracker Porter, and nowhere to be.',
    cats: ['nightlife', 'local', 'relaxed', 'outdoors'], tags: ['brewery', 'patio'],
    lat: 39.7589, lng: -105.0049, hood: 'LoHi', setting: 'mixed', price: 2, cost: '$7–9 a pint',
    dur: [45, 90],
    weekly: H.days({ 1: [{ open: t(12), close: t(22) }], 2: [{ open: t(12), close: t(22) }], 3: [{ open: t(12), close: t(22) }], 4: [{ open: t(12), close: t(22) }], 5: [{ open: t(12), close: t(23) }], 6: [{ open: t(11), close: t(23) }], 0: [{ open: t(11), close: t(22) }] }),
    exposure: 'partial',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: STREET_MOD, rating: 4.6,
  }),
  make({
    id: 'williams-graham', name: 'Williams & Graham',
    summary: 'Speakeasy behind a bookshelf in LoHi. Deep cocktail list, dim and quiet.',
    pitch: 'Put your name in, walk the neighborhood, come back when they text you.',
    cats: ['nightlife', 'romantic', 'weird', 'local'], tags: ['cocktails', 'speakeasy'],
    lat: 39.7576, lng: -105.01, hood: 'LoHi', setting: 'indoor', price: 3, cost: '$15–18 cocktails',
    dur: [60, 90], weekly: H.daily(t(17), t(25)), overrides: {}, exposure: 'none',
    attrs: { reservationRecommended: true, kidFriendly: false, accessible: false, walkable: true, transitFriendly: true },
    parking: NONE_HARD, rating: 4.7,
  }),
  make({
    id: 'ophelias', name: "Ophelia's Electric Soapbox",
    summary: 'Three-level gastro-brothel-turned-music-venue with a stage, bar and brunch.',
    pitch: 'Dinner that turns into a show without changing buildings.',
    cats: ['music', 'nightlife', 'food', 'weird'], tags: ['live music', 'venue'],
    lat: 39.7527, lng: -104.993, hood: 'LoDo', setting: 'indoor', price: 2, cost: '$20–40 · shows extra',
    dur: [90, 150],
    weekly: H.days({ 2: [{ open: t(16), close: t(24) }], 3: [{ open: t(16), close: t(24) }], 4: [{ open: t(16), close: t(25) }], 5: [{ open: t(16), close: t(26) }], 6: [{ open: t(10), close: t(26) }], 0: [{ open: t(10), close: t(23) }] }),
    exposure: 'none',
    attrs: { reservationRecommended: true, accessible: true, walkable: true, transitFriendly: true, kidFriendly: false },
    parking: GARAGE_HARD, rating: 4.5,
  }),
  make({
    id: 'milk-market', name: 'Denver Milk Market',
    summary: 'Sixteen concepts under one roof in the Dairy Block — ramen, pizza, cocktails, coffee.',
    pitch: 'The easiest group meal downtown. Open early, open late.',
    cats: ['food', 'local', 'coffee', 'family'], tags: ['food hall'],
    lat: 39.7541, lng: -104.9962, hood: 'LoDo', setting: 'indoor', price: 2, cost: '$12–25 per person',
    dur: [45, 75], weekly: H.daily(t(7), t(22)), exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: GARAGE_HARD, rating: 4.4,
  }),
  make({
    id: 'history-colorado', name: 'History Colorado Center',
    summary: 'Hands-on state history: a time machine, a ski-jump simulator, a 1920s mining town.',
    pitch: 'More fun than "history museum" sounds. Good for a rainy two hours.',
    cats: ['history', 'family', 'tourist'], tags: ['museum'],
    lat: 39.7355, lng: -104.988, hood: 'Golden Triangle', setting: 'indoor', price: 2, cost: '$15 adults · $10 kids',
    dur: [90, 150], weekly: H.daily(t(10), t(17)), activities: [museumLastEntry(t(17), 30)], exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, transitFriendly: true, walkable: true },
    parking: GARAGE_MOD, rating: 4.6,
  }),
  make({
    id: 'molly-brown', name: 'Molly Brown House Museum',
    summary: "The Unsinkable Molly Brown's Capitol Hill mansion, restored to 1910.",
    pitch: 'Short, charming, walkable from the Capitol. Last tour leaves at 3:30.',
    cats: ['history', 'tourist', 'relaxed'], tags: ['museum', 'house'],
    lat: 39.7378, lng: -104.9808, hood: 'Capitol Hill', setting: 'indoor', price: 2, cost: '$17 adults',
    dur: [45, 75],
    weekly: H.days({ 2: [{ open: t(10), close: t(16, 30) }], 3: [{ open: t(10), close: t(16, 30) }], 4: [{ open: t(10), close: t(16, 30) }], 5: [{ open: t(10), close: t(16, 30) }], 6: [{ open: t(10), close: t(16, 30) }], 0: [{ open: t(10), close: t(16, 30) }] }),
    activities: [{ label: 'Last tour', kind: 'lastEntry', mustCover: 'arrival', weekly: H.daily(t(10), t(15, 30)) }],
    exposure: 'none',
    attrs: { kidFriendly: true, accessible: false, walkable: true, transitFriendly: true },
    parking: STREET_MOD, rating: 4.6,
  }),
  make({
    id: 'clyfford-still', name: 'Clyfford Still Museum',
    summary: 'One artist, one quiet concrete building, next door to the DAM.',
    pitch: 'An hour of calm. Pair it with the Art Museum and lunch in the Golden Triangle.',
    cats: ['arts', 'relaxed', 'romantic'], tags: ['museum'],
    lat: 39.7366, lng: -104.9897, hood: 'Golden Triangle', setting: 'indoor', price: 2, cost: '$14 adults',
    dur: [45, 75],
    weekly: H.days({ 2: [{ open: t(10), close: t(17) }], 3: [{ open: t(10), close: t(17) }], 4: [{ open: t(10), close: t(17) }], 5: [{ open: t(10), close: t(20) }], 6: [{ open: t(10), close: t(17) }], 0: [{ open: t(10), close: t(17) }] }),
    exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: GARAGE_MOD, rating: 4.7,
  }),
  make({
    id: 'kirkland', name: 'Kirkland Museum of Fine & Decorative Art',
    summary: 'Salon-style jam of 20th-century design: Eames, Tiffany, Bauhaus, floor to ceiling.',
    pitch: 'Visually overwhelming in the best way. Ages 13+ only.',
    cats: ['arts', 'weird', 'relaxed'], tags: ['museum', 'design'],
    lat: 39.7359, lng: -104.9887, hood: 'Golden Triangle', setting: 'indoor', price: 2, cost: '$12 adults · 13+ only',
    dur: [45, 75],
    weekly: H.days({ 2: [{ open: t(11), close: t(17) }], 3: [{ open: t(11), close: t(17) }], 4: [{ open: t(11), close: t(17) }], 5: [{ open: t(11), close: t(17) }], 6: [{ open: t(11), close: t(17) }], 0: [{ open: t(11), close: t(17) }] }),
    exposure: 'none',
    attrs: { kidFriendly: false, accessible: true, walkable: true, transitFriendly: true },
    parking: STREET_MOD, rating: 4.7,
  }),
  make({
    id: 'forney', name: 'Forney Museum of Transportation',
    summary: 'Big Boy steam locomotive, Amelia Earhart\'s Kissel, and 600 other things with wheels.',
    pitch: 'Kids and gearheads both leave happy. Easy parking, never crowded.',
    cats: ['weird', 'history', 'family', 'local'], tags: ['museum'],
    lat: 39.7756, lng: -104.9715, hood: 'Five Points', setting: 'indoor', price: 2, cost: '$12 adults · $6 kids',
    dur: [60, 90],
    weekly: H.days({ 1: [{ open: t(10), close: t(17) }], 2: [{ open: t(10), close: t(17) }], 3: [{ open: t(10), close: t(17) }], 4: [{ open: t(10), close: t(17) }], 5: [{ open: t(10), close: t(17) }], 6: [{ open: t(10), close: t(17) }], 0: [{ open: t(12), close: t(17) }] }),
    exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, transitFriendly: false },
    parking: EASY_FREE, rating: 4.6,
  }),
  make({
    id: 'movement', name: 'Movement Climbing + Fitness — RiNo',
    summary: 'Big bouldering and rope gym with a day pass and rental gear.',
    pitch: 'The active rainy-day answer. Beginners are welcome; staff will get you going.',
    cats: ['active', 'sports', 'local'], tags: ['climbing', 'gym'],
    lat: 39.7667, lng: -104.9794, hood: 'RiNo', setting: 'indoor', price: 2, cost: '$28 day pass + rentals',
    dur: [60, 120], weekly: H.days({ 1: [{ open: t(6), close: t(22) }], 2: [{ open: t(6), close: t(22) }], 3: [{ open: t(6), close: t(22) }], 4: [{ open: t(6), close: t(22) }], 5: [{ open: t(6), close: t(22) }], 6: [{ open: t(8), close: t(20) }], 0: [{ open: t(8), close: t(20) }] }),
    exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, transitFriendly: true, walkable: true },
    parking: EASY_LOT, rating: 4.7,
  }),
  make({
    id: 'skatepark', name: 'Denver Skatepark',
    summary: '60,000 square feet of free concrete by the river, with the skyline behind it.',
    pitch: 'Skate, scoot, or just watch. One of the best city skateparks anywhere.',
    cats: ['active', 'sports', 'outdoors', 'local'], tags: ['skate'],
    lat: 39.7579, lng: -105.0016, hood: 'Platte Valley', setting: 'outdoor', price: 0,
    dur: [30, 75], weekly: H.daily(t(5), t(23)), overrides: {}, exposure: 'full',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true, dogFriendly: true },
    parking: EASY_FREE, rating: 4.7,
  }),
  make({
    id: 'confluence', name: 'Confluence Park & Cherry Creek Trail',
    summary: 'Where the city started: a river confluence, kayak chutes and miles of paved trail.',
    pitch: 'Rent a bike or just walk the creek path to Larimer. Dogs, strollers, everyone.',
    cats: ['outdoors', 'active', 'scenic', 'family', 'local'], tags: ['trail', 'bike'],
    lat: 39.7545, lng: -105.0075, hood: 'Platte Valley', setting: 'outdoor', price: 0,
    dur: [45, 90], weekly: H.daily(t(5), t(23)), overrides: {}, exposure: 'full',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: STREET_MOD, rating: 4.7,
  }),
  make({
    id: 'lookout', name: 'Lookout Mountain & Buffalo Bill Museum',
    summary: 'Twisty road up to Buffalo Bill\'s grave with a 100-mile view over the plains.',
    pitch: 'The quickest big view from the city. Sunset here is a cheat code.',
    cats: ['scenic', 'history', 'tourist', 'outdoors'], tags: ['viewpoint'],
    lat: 39.7322, lng: -105.2393, hood: 'Golden', setting: 'mixed', price: 1, cost: 'Museum $5 · view free',
    dur: [45, 90],
    weekly: H.daily(t(9), t(17)),
    exposure: 'partial',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: true, transitFriendly: false },
    parking: EASY_FREE, rating: 4.7,
  }),
  make({
    id: 'elitch', name: 'Elitch Gardens',
    summary: 'Downtown theme and water park. Weekends only in the fall, closed in winter.',
    pitch: 'Coasters with a skyline backdrop. Check the calendar — fall is weekends only.',
    cats: ['family', 'active', 'tourist'], tags: ['theme park'],
    lat: 39.7503, lng: -105.0101, hood: 'Platte Valley', setting: 'outdoor', price: 4, cost: '$60–75',
    dur: [240, 360],
    weekly: H.days({ 6: [{ open: t(10, 30), close: t(20) }], 0: [{ open: t(10, 30), close: t(19) }] }),
    season: { from: '04-25', to: '10-31' }, exposure: 'full',
    attrs: { kidFriendly: true, accessible: true, transitFriendly: true },
    parking: { difficulty: 'easy', cost: '$25 lot', type: 'lot', walkMin: 6 }, rating: 4.2,
  }),
  make({
    id: 'lakeside', name: 'Lakeside Amusement Park',
    summary: 'A 1908 amusement park with a wooden coaster and neon, open summers only.',
    pitch: 'Time-capsule charm. Cheap rides, great at night. Summer season only.',
    cats: ['weird', 'family', 'local', 'tourist'], tags: ['amusement park'],
    lat: 39.7791, lng: -105.0549, hood: 'Lakeside', setting: 'outdoor', price: 1, cost: '$5 gate + ride tickets',
    dur: [120, 180], weekly: H.days({ 5: [{ open: t(18), close: t(23) }], 6: [{ open: t(12), close: t(23) }], 0: [{ open: t(12), close: t(23) }] }),
    season: { from: '05-15', to: '09-15' }, exposure: 'full',
    attrs: { kidFriendly: true, accessible: false, transitFriendly: false },
    parking: EASY_FREE, rating: 4.3,
  }),
  make({
    id: 'firefighters', name: 'Denver Firefighters Museum',
    summary: 'Historic 1909 firehouse with engines, poles and gear to try on.',
    pitch: 'Small, hands-on, and great with kids — when it reopens.',
    cats: ['history', 'family', 'local'], tags: ['museum'],
    lat: 39.7436, lng: -104.9908, hood: 'Downtown', setting: 'indoor', price: 1, cost: '$8',
    dur: [45, 60], weekly: H.days({ 1: [{ open: t(10), close: t(16) }], 2: [{ open: t(10), close: t(16) }], 3: [{ open: t(10), close: t(16) }], 4: [{ open: t(10), close: t(16) }], 5: [{ open: t(10), close: t(16) }], 6: [{ open: t(10), close: t(16) }] }),
    temporarilyClosed: true, exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: GARAGE_MOD, rating: 4.5,
  }),
  make({
    id: 'urban-putt', name: 'Urban Putt',
    summary: 'Indoor mini golf with a bar in a historic downtown building.',
    pitch: 'Fun, but we couldn\'t confirm current hours — so DayOut won\'t recommend it.',
    cats: ['family', 'weird', 'nightlife', 'active'], tags: ['mini golf'],
    lat: 39.7445, lng: -104.9957, hood: 'Downtown', setting: 'indoor', price: 2, cost: '$15–18',
    dur: [60, 90], weekly: H.daily(t(12), t(23)), unknownHours: true, exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: GARAGE_HARD, rating: 4.4,
  }),
  make({
    id: 'cherry-creek-mall', name: 'Cherry Creek Shopping Center',
    summary: 'The upscale mall, plus the walkable Cherry Creek North district across the street.',
    pitch: 'Indoor browsing with easy free parking, then dinner in Cherry Creek North.',
    cats: ['shopping', 'relaxed', 'food'], tags: ['mall'],
    lat: 39.7174, lng: -104.9532, hood: 'Cherry Creek', setting: 'indoor', price: 3,
    dur: [60, 120],
    weekly: H.days({ 1: [{ open: t(10), close: t(20) }], 2: [{ open: t(10), close: t(20) }], 3: [{ open: t(10), close: t(20) }], 4: [{ open: t(10), close: t(20) }], 5: [{ open: t(10), close: t(20) }], 6: [{ open: t(10), close: t(20) }], 0: [{ open: t(11), close: t(18) }] }),
    exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, transitFriendly: true },
    parking: { difficulty: 'easy', cost: 'Free garage', type: 'garage', walkMin: 3 }, rating: 4.4,
  }),
  make({
    id: 'pearl-market', name: 'South Pearl Street Farmers Market',
    summary: 'Sunday-morning market on a leafy block: produce, pastries, music, dogs.',
    pitch: 'The most Denver way to spend a Sunday morning. May through November.',
    cats: ['local', 'food', 'outdoors', 'family', 'relaxed'], tags: ['market', 'event'],
    lat: 39.7049, lng: -104.9795, hood: 'Platt Park', setting: 'outdoor', price: 1,
    dur: [45, 90], weekly: H.days({ 0: [{ open: t(9), close: t(13) }] }), season: { from: '05-01', to: '11-15' },
    exposure: 'full',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: STREET_MOD, rating: 4.8,
  }),
  make({
    id: 'stranahans', name: "Stranahan's Whiskey Distillery Tour",
    summary: 'Tour and tasting at the Colorado single malt distillery south of downtown.',
    pitch: 'An hour, a pour, and a good story. Tours book out — reserve ahead.',
    cats: ['nightlife', 'local', 'relaxed', 'romantic'], tags: ['tour', 'whiskey'],
    lat: 39.7047, lng: -104.9995, hood: 'Overland', setting: 'indoor', price: 2, cost: '$20 tour',
    dur: [60, 75],
    weekly: H.days({ 2: [{ open: t(12), close: t(20) }], 3: [{ open: t(12), close: t(20) }], 4: [{ open: t(12), close: t(20) }], 5: [{ open: t(12), close: t(21) }], 6: [{ open: t(12), close: t(21) }], 0: [{ open: t(12), close: t(18) }] }),
    activities: [{ label: 'Last tour', kind: 'lastEntry', mustCover: 'arrival', weekly: H.days({ 2: [{ open: t(12), close: t(18, 30) }], 3: [{ open: t(12), close: t(18, 30) }], 4: [{ open: t(12), close: t(18, 30) }], 5: [{ open: t(12), close: t(19, 30) }], 6: [{ open: t(12), close: t(19, 30) }], 0: [{ open: t(12), close: t(16, 30) }] }) }],
    exposure: 'none',
    attrs: { reservationRequired: true, kidFriendly: false, accessible: true, transitFriendly: false },
    parking: EASY_FREE, rating: 4.7,
  }),
  make({
    id: 'hammonds', name: "Hammond's Candies Factory Tour",
    summary: 'Free 30-minute tour of a 100-year-old candy cane factory in north Denver.',
    pitch: 'Free, sweet, and oddly fascinating. Weekdays only.',
    cats: ['family', 'weird', 'local', 'tourist'], tags: ['tour', 'free'],
    lat: 39.8008, lng: -104.9774, hood: 'North Denver', setting: 'indoor', price: 0, cost: 'Free',
    dur: [30, 60],
    weekly: H.days({ 1: [{ open: t(10), close: t(15) }], 2: [{ open: t(10), close: t(15) }], 3: [{ open: t(10), close: t(15) }], 4: [{ open: t(10), close: t(15) }], 5: [{ open: t(10), close: t(15) }] }),
    exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, transitFriendly: false },
    parking: EASY_FREE, rating: 4.6,
  }),
  make({
    id: 'sloans', name: "Sloan's Lake Park",
    summary: 'Big lake, 2.6-mile loop, and the best skyline-plus-mountains sunset in the city limits.',
    pitch: 'Bring the dog and a coffee. Sunset from the east shore.',
    cats: ['outdoors', 'scenic', 'relaxed', 'active', 'local'], tags: ['park', 'lake'],
    lat: 39.7485, lng: -105.0455, hood: "Sloan's Lake", setting: 'outdoor', price: 0,
    dur: [45, 90], weekly: H.daily(t(5), t(23)), overrides: {}, exposure: 'full',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: true, walkable: true, transitFriendly: false },
    parking: EASY_FREE, rating: 4.7,
  }),
  make({
    id: 'stanley', name: 'Stanley Marketplace',
    summary: 'A converted aviation hangar in Aurora with 50 local shops and restaurants.',
    pitch: 'Easy parking, everything under one roof, and nobody from out of town knows about it.',
    cats: ['food', 'shopping', 'local', 'family', 'coffee'], tags: ['market'],
    lat: 39.7797, lng: -104.8914, hood: 'Aurora', setting: 'indoor', price: 2,
    dur: [60, 120], weekly: H.daily(t(7), t(21)), exposure: 'none',
    attrs: { kidFriendly: true, accessible: true, dogFriendly: true, transitFriendly: false },
    parking: EASY_FREE, rating: 4.6,
  }),
  make({
    id: 'indian-springs', name: 'Indian Hot Springs',
    summary: 'Geothermal pool under a greenhouse dome in Idaho Springs, 35 miles up I-70.',
    pitch: 'Soak in a jungle dome in the mountains. Watch I-70 traffic — it can double the drive.',
    cats: ['relaxed', 'romantic', 'weird', 'outdoors'], tags: ['hot springs'],
    lat: 39.7423, lng: -105.5121, hood: 'Idaho Springs', setting: 'mixed', price: 2, cost: '$26–32',
    dur: [90, 150], weekly: H.daily(t(9), t(22)), overrides: {}, exposure: 'none',
    attrs: { kidFriendly: true, accessible: false, transitFriendly: false },
    parking: EASY_FREE, rating: 4.3,
  }),
  make({
    id: 'coors-tour', name: 'Coors Brewery Tour',
    summary: 'The world\'s largest single-site brewery, in Golden, with a free tasting at the end.',
    pitch: 'Classic Colorado. Reserve a time slot, then wander Golden\'s main street after.',
    cats: ['tourist', 'local', 'nightlife', 'history'], tags: ['tour', 'brewery'],
    lat: 39.7556, lng: -105.2131, hood: 'Golden', setting: 'indoor', price: 1, cost: '$10 (21+) · $5 (under 21)',
    dur: [60, 90],
    weekly: H.days({ 4: [{ open: t(10), close: t(16) }], 5: [{ open: t(10), close: t(16) }], 6: [{ open: t(10), close: t(16) }], 0: [{ open: t(10), close: t(16) }], 1: [{ open: t(10), close: t(16) }] }),
    activities: [{ label: 'Last tour', kind: 'lastEntry', mustCover: 'arrival', weekly: H.daily(t(10), t(15)) }],
    exposure: 'none',
    attrs: { reservationRequired: true, kidFriendly: true, accessible: true, transitFriendly: false },
    parking: EASY_FREE, rating: 4.5,
  }),
  make({
    id: 'pearl-street', name: 'Pearl Street Mall, Boulder',
    summary: 'Boulder\'s brick pedestrian mall: buskers, bookstores, the Flatirons at the end of the street.',
    pitch: 'Worth the 30-mile drive on a nice day. Add a Chautauqua walk if you have time.',
    cats: ['shopping', 'tourist', 'food', 'scenic', 'outdoors'], tags: ['district'],
    lat: 40.0176, lng: -105.2797, hood: 'Boulder', setting: 'mixed', price: 2,
    dur: [90, 180], weekly: H.daily(t(9), t(22)), overrides: {}, exposure: 'partial',
    attrs: { dogFriendly: true, kidFriendly: true, accessible: true, walkable: true, transitFriendly: true },
    parking: GARAGE_MOD, rating: 4.7,
  }),
];

export function findDemoPlace(id: string): Place | undefined {
  return DENVER_PLACES.find((p) => p.id === id);
}
